name = "proxycontroller2"
main = "src/index.js"
compatibility_date = "2026-06-03"

# 普通 Worker
workers_dev = true

# 保留 Cloudflare Dashboard 中已经配置的环境变量
keep_vars = true

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "proxy_db"
database_id = "e1e43df6-9cce-4308-9fac-4052e668b512"
